CREATE TABLE MEMBER_INFO
(
   ID INTEGER PRIMARY KEY,
   NAME VARCHAR NOT NULL,
   LOGIN_ID VARCHAR NOT NULL,
   LOGIN_PW VARCHAR NOT NULL
)

CREATE TABLE TEMPLATE
(
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    MEMBER_ID INTEGER FOREIGN KEY NOT NULL
)

CREATE TABLE ENTITY
(
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    MEMBER_ID INTEGER FOREIGN KEY NOT NULL
)

CREATE TABLE COLUMN
(
    ID INTEGER PRIMARY KEY,
    TEMPLATE_ID INTEGER FOREIGN KEY,
    ENTITY_ID INTEGER FOREIGN KEY,
    NAME VARCHAR NOT NULL,
    TYPE VARCHAR NOT NULL
)