CREATE TABLE MEMBER
(
   ID INTEGER PRIMARY KEY,
   NAME VARCHAR NOT NULL,
   LOGIN_ID VARCHAR NOT NULL,
   LOGIN_PW VARCHAR NOT NULL
);

CREATE TABLE TEMPLATE
(
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    MEMBER_ID INTEGER REFERENCES MEMBER NOT NULL
);

CREATE TABLE ENTITY
(
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    MEMBER_ID INTEGER REFERENCES MEMBER NOT NULL
);

CREATE TABLE COLUMN
(
    ID INTEGER PRIMARY KEY,
    TEMPLATE_ID INTEGER REFERENCES ENTITY NOT NULL,
    ENTITY_ID INTEGER REFERENCES ENTITY NOT NULL,
    NAME VARCHAR NOT NULL,
    TYPE VARCHAR NOT NULL,
    COND VARCHAR NOT NULL
);