CREATE TABLE MEMBER
(
   ID INTEGER PRIMARY KEY AUTO_INCREMENT,
   NAME VARCHAR NOT NULL,
   FILE_ID VARCHAR NOT NULL,
   LOGIN_ID VARCHAR NOT NULL,
   LOGIN_PW VARCHAR NOT NULL
);

CREATE TABLE TEMPLATE
(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR NOT NULL,
    MEMBER_ID VARCHAR NOT NULL REFERENCES MEMBER(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ENTITY
(
    ID INTEGER PRIMARY KEY,
    FILE_NAME VARCHAR NOT NULL,
    FILE_DOMAIN VARCHAR NOT NULL,
    FOREIGN KEY(ID) REFERENCES TEMPLATE(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE DOCUMENT
(
    ID VARCHAR PRIMARY KEY,
    TYPE VARCHAR NOT NULL,
    TEMPLATE_ID INTEGER NOT NULL,
    FOREIGN KEY(TEMPLATE_ID) REFERENCES TEMPLATE(ID)
);

CREATE TABLE QUERY
(
    ID INTEGER PRIMARY,
    FOREIGN KEY(ID) REFERENCES TEMPLATE(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE COLUMN
(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ENTITY_ID INTEGER REFERENCES ENTITY(ID) ON DELETE CASCADE NOT NULL,
    NAME VARCHAR NOT NULL,
    TYPE VARCHAR NOT NULL
);

CREATE TABLE KEY_CONDITION
(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    TYPE VARCHAR NOT NULL,
    COLUMN_ID INTEGER REFERENCES COLUMN(ID) ON DELETE CASCADE NOT NULL
);

CREATE TABLE VALUE_CONDITION
(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    TYPE VARCHAR NOT NULL,
    COLUMN_ID INTEGER REFERENCES COLUMN(ID) ON DELETE CASCADE NOT NULL,
    TERM VARCHAR NOT NULL
);
